### ISSUE TITLE
💚 🐛 CI empty file and no style

### ISSUE THREAD

**Issue by Emerson452** [Popoyoko/tokenscript#8]
- [x] Github action is bugged, i don't know why the file "token.json" don't go in the style branch.
- [x] In style branch and variales branch, there is a .nojekyll with no content fille

**Comment by LouiFi** [comment]
✅ DONE !

Damn, 4 hours of work 😭 this was really hard to manage !  [Check out the workflow history 🤣](https://github.com/Popoyoko/tokenscript/actions)

But here it is ! => [Resolving commit](https://github.com/Popoyoko/tokenscript/commit/602a616d2e074954c6d1be60ae74103a79e62477)
